### ISSUE TITLE
Trino fails to start if Hive-metastore replica is more than 1

### ISSUE THREAD

**Issue by zaultooz** [stackabletech/trino-operator#343]
Hey

A potential bug I spotted.

##BUG##
Trino fails to start throwing an error with URI parsing if the Hive-metastore contains multiple thrift urls. Error log:
``` JAVA
1) Error: Error invoking configuration method [public StaticMetastoreConfig StaticMetastoreConfig.setMetastoreUris(String)]

1 error

======================
Full classname legend:
======================
StaticMetastoreConfig: "io.trino.plugin.hive.metastore.thrift.StaticMetastoreConfig"
========================
End of classname legend:
========================

io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Error invoking configuration method [public StaticMetastoreConfig StaticMetastoreConfig.setMetastoreUris(String)]

1 error

======================
Full classname legend:
======================
StaticMetastoreConfig: "io.trino.plugin.hive.metastore.thrift.StaticMetastoreConfig"
========================
End of classname legend:
========================

	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:234)
	at io.trino.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:137)
	at io.trino.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.trino.plugin.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:66)
	at io.trino.connector.DefaultCatalogFactory.createConnector(DefaultCatalogFactory.java:201)
	at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:123)
	at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:44)
	at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:139)
	at io.trino.server.Server.doStart(Server.java:139)
	at io.trino.server.Server.lambda$start$0(Server.java:88)
	at io.trino.$gen.Trino_396____20221110_095610_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:88)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 9: thrift://some-hive-metastore-default-0.some-hive-metastore-default.some-cluster.svc.cluster.local:9083
thrift://some-hive-metastore-default-1.some-hive-metastore-default.some-cluster.svc.cluster.local:9083
```

## Steps to Reproduce ##
1. Create a hive-metastore with a replica greater than 1.
2. Create a trino-cluster with a catalog pointing to the hive-metastore's discovery configmap.
You should be able to see a similar error appear in the Trino coordinator and worker logs.

## Workaround ##
Use hive-metastore with 1 replica.

**Comment by lfrancke** [comment]
Thank you for the report. That is indeed a bug and we'll fix it for our next release.
We'll use this ticket for updates.

**Comment by maltesander** [comment]
## Refinement:

Trino expects multiple Hive metastore instances comma-separated (https://trino.io/docs/current/connector/hive.html#metastore-configuration-properties).

By default will pick the first URL in this list (or any later URL if the first one is not reachable).

## TODO:
- [ ] Adapt Trino Operator to retrieve the Hive Metastore URLs from the discovery ConfigMap and add them to the "hive.metastore" property in a comma-separated list
- [ ] Optional: Shuffle the Hive Metastore URLs for random access (needs discussion)
